# Generated by Django 5.2.12 on 2026-04-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=32, null=True)),
                ('tipo_pagamento', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
    ]
