# Generated by Django 5.2.12 on 2026-04-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
