# Generated by Django 5.2.12 on 2026-04-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_usuario_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF', max_length=14, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
