# Generated by Django 5.2.12 on 2026-06-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_roupa'),
        ('core', '0008_user_cpf'),
    ]

    operations = [
    ]
