# Generated by Django 5.2.12 on 2026-04-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_compra_tipo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='preco',
        ),
    ]
