# Generated by Django 5.2.15 on 2026-06-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0006_roupa_0008_user_cpf'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
