# Generated by Django 5.2.12 on 2026-06-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_continente'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='continente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.continente'),
        ),
    ]
