# Generated by Django 5.2.12 on 2026-06-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_venda'),
        ('core', '0009_remove_compra_nome_remove_compra_preco'),
        ('core', '0013_roupa_categoria'),
    ]

    operations = [
    ]
