# Generated by Django 5.2.12 on 2026-06-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260612_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compra'),
        ),
        migrations.AddField(
            model_name='user',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venda'),
        ),
    ]
