# Generated by Django 5.2.12 on 2026-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_compra_user_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipoPagamento', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
