# Generated by Django 5.2.12 on 2026-06-23 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tamanho_alter_roupa_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
