# Generated by Django 5.2.12 on 2026-06-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tipopagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipoPagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopagamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipoPagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopagamento'),
        ),
    ]
