# Generated by Django 5.2.12 on 2026-06-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_venda_data_venda'),
        ('core', '0017_compra_tipopagamento_venda_tipopagamento'),
    ]

    operations = [
    ]
