# Generated by Django 5.2.12 on 2026-06-30 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260623_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='venda',
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
