# Generated by Django 5.2.12 on 2026-07-01 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_user_compra_remove_user_venda_compra_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
            ],
            options={
                'verbose_name_plural': 'Status de Entrega',
            },
        ),
    ]
