# Generated by Django 5.2.12 on 2026-07-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_favorito'),
        ('core', '0019_fornecedor_comprafornecedor_itemcomprafornecedor'),
        ('core', '0020_itemvenda_remove_venda_tipopagamento_and_more'),
        ('core', '0020_remove_estoque_categoria_alter_estoque_quantidade_and_more'),
        ('core', '0020_statusentrega'),
    ]

    operations = [
    ]
