# Generated by Django 5.2.12 on 2026-07-03 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20260703_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='cor',
        ),
        migrations.AddField(
            model_name='favorito',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
