# Generated by Django 5.2.15 on 2026-07-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_roupa_foto'),
        ('core', '0022_remove_favorito_comentario_remove_favorito_nota_and_more'),
    ]

    operations = [
    ]
