# Generated by Django 5.2.15 on 2026-07-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260715_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'roupa')},
        ),
    ]
