# Generated by Django 5.2.15 on 2026-09-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260909_1641'),
        ('core', '0024_alter_favorito_unique_together'),
    ]

    operations = [
    ]
