# Generated by Django 5.2.15 on 2026-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20260929_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='cor',
            field=models.CharField(default='sem cor', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roupa',
            name='cor_hex',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
